var dir_4eff9271cac5e78b7b7ce1f809f6370b =
[
    [ "nrf_bitmask.h", "modules_2nrfx_2drivers_2include_2nrf__bitmask_8h.html", "modules_2nrfx_2drivers_2include_2nrf__bitmask_8h" ],
    [ "nrfx_adc.h", "nrfx__adc_8h.html", "nrfx__adc_8h" ],
    [ "nrfx_clock.h", "nrfx__clock_8h.html", "nrfx__clock_8h" ],
    [ "nrfx_comp.h", "nrfx__comp_8h.html", "nrfx__comp_8h" ],
    [ "nrfx_gpiote.h", "nrfx__gpiote_8h.html", "nrfx__gpiote_8h" ],
    [ "nrfx_i2s.h", "nrfx__i2s_8h.html", "nrfx__i2s_8h" ],
    [ "nrfx_lpcomp.h", "nrfx__lpcomp_8h.html", "nrfx__lpcomp_8h" ],
    [ "nrfx_pdm.h", "nrfx__pdm_8h.html", "nrfx__pdm_8h" ],
    [ "nrfx_power.h", "nrfx__power_8h.html", "nrfx__power_8h" ],
    [ "nrfx_power_clock.h", "nrfx__power__clock_8h.html", "nrfx__power__clock_8h" ],
    [ "nrfx_ppi.h", "nrfx__ppi_8h.html", "nrfx__ppi_8h" ],
    [ "nrfx_pwm.h", "nrfx__pwm_8h.html", "nrfx__pwm_8h" ],
    [ "nrfx_qdec.h", "nrfx__qdec_8h.html", "nrfx__qdec_8h" ],
    [ "nrfx_qspi.h", "nrfx__qspi_8h.html", "nrfx__qspi_8h" ],
    [ "nrfx_rng.h", "nrfx__rng_8h.html", "nrfx__rng_8h" ],
    [ "nrfx_rtc.h", "nrfx__rtc_8h.html", "nrfx__rtc_8h" ],
    [ "nrfx_saadc.h", "nrfx__saadc_8h.html", "nrfx__saadc_8h" ],
    [ "nrfx_spi.h", "nrfx__spi_8h.html", "nrfx__spi_8h" ],
    [ "nrfx_spim.h", "nrfx__spim_8h.html", "nrfx__spim_8h" ],
    [ "nrfx_spis.h", "nrfx__spis_8h.html", "nrfx__spis_8h" ],
    [ "nrfx_swi.h", "nrfx__swi_8h.html", "nrfx__swi_8h" ],
    [ "nrfx_systick.h", "nrfx__systick_8h.html", "nrfx__systick_8h" ],
    [ "nrfx_timer.h", "nrfx__timer_8h.html", "nrfx__timer_8h" ],
    [ "nrfx_twi.h", "nrfx__twi_8h.html", "nrfx__twi_8h" ],
    [ "nrfx_twim.h", "nrfx__twim_8h.html", "nrfx__twim_8h" ],
    [ "nrfx_twis.h", "nrfx__twis_8h.html", "nrfx__twis_8h" ],
    [ "nrfx_uart.h", "nrfx__uart_8h.html", "nrfx__uart_8h" ],
    [ "nrfx_uarte.h", "nrfx__uarte_8h.html", "nrfx__uarte_8h" ],
    [ "nrfx_wdt.h", "nrfx__wdt_8h.html", "nrfx__wdt_8h" ]
];