var dir_f4dbfb2b47adc6a696ff80527b5c4bac =
[
    [ "nrf_adc.h", "nrf__adc_8h.html", "nrf__adc_8h" ],
    [ "nrf_clock.h", "nrf__clock_8h.html", "nrf__clock_8h" ],
    [ "nrf_comp.h", "nrf__comp_8h.html", "nrf__comp_8h" ],
    [ "nrf_ecb.c", "nrf__ecb_8c.html", "nrf__ecb_8c" ],
    [ "nrf_ecb.h", "nrf__ecb_8h.html", "nrf__ecb_8h" ],
    [ "nrf_egu.h", "nrf__egu_8h.html", "nrf__egu_8h" ],
    [ "nrf_gpio.h", "nrf__gpio_8h.html", "nrf__gpio_8h" ],
    [ "nrf_gpiote.h", "nrf__gpiote_8h.html", "nrf__gpiote_8h" ],
    [ "nrf_i2s.h", "nrf__i2s_8h.html", "nrf__i2s_8h" ],
    [ "nrf_lpcomp.h", "nrf__lpcomp_8h.html", "nrf__lpcomp_8h" ],
    [ "nrf_nvmc.c", "nrf__nvmc_8c.html", "nrf__nvmc_8c" ],
    [ "nrf_nvmc.h", "nrf__nvmc_8h.html", "nrf__nvmc_8h" ],
    [ "nrf_pdm.h", "nrf__pdm_8h.html", "nrf__pdm_8h" ],
    [ "nrf_power.h", "nrf__power_8h.html", "nrf__power_8h" ],
    [ "nrf_ppi.h", "nrf__ppi_8h.html", "nrf__ppi_8h" ],
    [ "nrf_pwm.h", "nrf__pwm_8h.html", "nrf__pwm_8h" ],
    [ "nrf_qdec.h", "nrf__qdec_8h.html", "nrf__qdec_8h" ],
    [ "nrf_qspi.h", "nrf__qspi_8h.html", "nrf__qspi_8h" ],
    [ "nrf_rng.h", "nrf__rng_8h.html", "nrf__rng_8h" ],
    [ "nrf_rtc.h", "nrf__rtc_8h.html", "nrf__rtc_8h" ],
    [ "nrf_saadc.h", "nrf__saadc_8h.html", "nrf__saadc_8h" ],
    [ "nrf_spi.h", "nrf__spi_8h.html", "nrf__spi_8h" ],
    [ "nrf_spim.h", "nrf__spim_8h.html", "nrf__spim_8h" ],
    [ "nrf_spis.h", "nrf__spis_8h.html", "nrf__spis_8h" ],
    [ "nrf_systick.h", "nrf__systick_8h.html", "nrf__systick_8h" ],
    [ "nrf_temp.h", "nrf__temp_8h.html", "nrf__temp_8h" ],
    [ "nrf_timer.h", "nrf__timer_8h.html", "nrf__timer_8h" ],
    [ "nrf_twi.h", "nrf__twi_8h.html", "nrf__twi_8h" ],
    [ "nrf_twim.h", "nrf__twim_8h.html", "nrf__twim_8h" ],
    [ "nrf_twis.h", "nrf__twis_8h.html", "nrf__twis_8h" ],
    [ "nrf_uart.h", "nrf__uart_8h.html", "nrf__uart_8h" ],
    [ "nrf_uarte.h", "nrf__uarte_8h.html", "nrf__uarte_8h" ],
    [ "nrf_usbd.h", "nrf__usbd_8h.html", "nrf__usbd_8h" ],
    [ "nrf_wdt.h", "nrf__wdt_8h.html", "nrf__wdt_8h" ]
];