var group___b_l_e___g_a_p___d_e_f_i_n_e_s =
[
    [ "SVC return values specific to GAP", "group___b_l_e___e_r_r_o_r_s___g_a_p.html", "group___b_l_e___e_r_r_o_r_s___g_a_p" ],
    [ "GAP Roles", "group___b_l_e___g_a_p___r_o_l_e_s.html", "group___b_l_e___g_a_p___r_o_l_e_s" ],
    [ "GAP Timeout sources", "group___b_l_e___g_a_p___t_i_m_e_o_u_t___s_o_u_r_c_e_s.html", "group___b_l_e___g_a_p___t_i_m_e_o_u_t___s_o_u_r_c_e_s" ],
    [ "GAP Address types", "group___b_l_e___g_a_p___a_d_d_r___t_y_p_e_s.html", "group___b_l_e___g_a_p___a_d_d_r___t_y_p_e_s" ],
    [ "Privacy modes", "group___b_l_e___g_a_p___p_r_i_v_a_c_y___m_o_d_e_s.html", "group___b_l_e___g_a_p___p_r_i_v_a_c_y___m_o_d_e_s" ],
    [ "Advertising data sizes.", "group___b_l_e___g_a_p___a_d_v___s_e_t___d_a_t_a___s_i_z_e_s.html", "group___b_l_e___g_a_p___a_d_v___s_e_t___d_a_t_a___s_i_z_e_s" ],
    [ "GAP Advertising Set Terminated reasons", "group___b_l_e___g_a_p___e_v_t___a_d_v___s_e_t___t_e_r_m_i_n_a_t_e_d___r_e_a_s_o_n.html", "group___b_l_e___g_a_p___e_v_t___a_d_v___s_e_t___t_e_r_m_i_n_a_t_e_d___r_e_a_s_o_n" ],
    [ "GAP Advertising and Scan Response Data format", "group___b_l_e___g_a_p___a_d___t_y_p_e___d_e_f_i_n_i_t_i_o_n_s.html", "group___b_l_e___g_a_p___a_d___t_y_p_e___d_e_f_i_n_i_t_i_o_n_s" ],
    [ "GAP Advertisement Flags", "group___b_l_e___g_a_p___a_d_v___f_l_a_g_s.html", "group___b_l_e___g_a_p___a_d_v___f_l_a_g_s" ],
    [ "GAP Advertising interval max and min", "group___b_l_e___g_a_p___a_d_v___i_n_t_e_r_v_a_l_s.html", "group___b_l_e___g_a_p___a_d_v___i_n_t_e_r_v_a_l_s" ],
    [ "GAP Advertising types", "group___b_l_e___g_a_p___a_d_v___t_y_p_e_s.html", "group___b_l_e___g_a_p___a_d_v___t_y_p_e_s" ],
    [ "GAP Advertising filter policies", "group___b_l_e___g_a_p___a_d_v___f_i_l_t_e_r___p_o_l_i_c_i_e_s.html", "group___b_l_e___g_a_p___a_d_v___f_i_l_t_e_r___p_o_l_i_c_i_e_s" ],
    [ "GAP Advertising timeout values in 10 ms units", "group___b_l_e___g_a_p___a_d_v___t_i_m_e_o_u_t___v_a_l_u_e_s.html", "group___b_l_e___g_a_p___a_d_v___t_i_m_e_o_u_t___v_a_l_u_e_s" ],
    [ "GAP Discovery modes", "group___b_l_e___g_a_p___d_i_s_c___m_o_d_e_s.html", "group___b_l_e___g_a_p___d_i_s_c___m_o_d_e_s" ],
    [ "GAP IO Capabilities", "group___b_l_e___g_a_p___i_o___c_a_p_s.html", "group___b_l_e___g_a_p___i_o___c_a_p_s" ],
    [ "GAP Authentication Key Types", "group___b_l_e___g_a_p___a_u_t_h___k_e_y___t_y_p_e_s.html", "group___b_l_e___g_a_p___a_u_t_h___k_e_y___t_y_p_e_s" ],
    [ "GAP Keypress Notification Types", "group___b_l_e___g_a_p___k_p___n_o_t___t_y_p_e_s.html", "group___b_l_e___g_a_p___k_p___n_o_t___t_y_p_e_s" ],
    [ "GAP Security status", "group___b_l_e___g_a_p___s_e_c___s_t_a_t_u_s.html", "group___b_l_e___g_a_p___s_e_c___s_t_a_t_u_s" ],
    [ "GAP Security status sources", "group___b_l_e___g_a_p___s_e_c___s_t_a_t_u_s___s_o_u_r_c_e_s.html", "group___b_l_e___g_a_p___s_e_c___s_t_a_t_u_s___s_o_u_r_c_e_s" ],
    [ "GAP Connection Parameters Limits", "group___b_l_e___g_a_p___c_p___l_i_m_i_t_s.html", "group___b_l_e___g_a_p___c_p___l_i_m_i_t_s" ],
    [ "GAP device name defines.", "group___b_l_e___g_a_p___d_e_v_n_a_m_e.html", "group___b_l_e___g_a_p___d_e_v_n_a_m_e" ],
    [ "GAP PHYs", "group___b_l_e___g_a_p___p_h_y_s.html", "group___b_l_e___g_a_p___p_h_y_s" ],
    [ "GAP attribute security requirement setters", "group___b_l_e___g_a_p___c_o_n_n___s_e_c___m_o_d_e___s_e_t___m_a_c_r_o_s.html", "group___b_l_e___g_a_p___c_o_n_n___s_e_c___m_o_d_e___s_e_t___m_a_c_r_o_s" ],
    [ "GAP event length defines.", "group___b_l_e___g_a_p___e_v_e_n_t___l_e_n_g_t_h.html", "group___b_l_e___g_a_p___e_v_e_n_t___l_e_n_g_t_h" ],
    [ "GAP concurrent connection count defines.", "group___b_l_e___g_a_p___r_o_l_e___c_o_u_n_t.html", "group___b_l_e___g_a_p___r_o_l_e___c_o_u_n_t" ],
    [ "Authenticated payload timeout defines.", "group___b_l_e___g_a_p___a_u_t_h___p_a_y_l_o_a_d___t_i_m_e_o_u_t.html", "group___b_l_e___g_a_p___a_u_t_h___p_a_y_l_o_a_d___t_i_m_e_o_u_t" ],
    [ "GAP Security Modes", "group___g_a_p___s_e_c___m_o_d_e_s.html", "group___g_a_p___s_e_c___m_o_d_e_s" ],
    [ "GAP Scan interval max and min", "group___b_l_e___g_a_p___s_c_a_n___i_n_t_e_r_v_a_l_s.html", "group___b_l_e___g_a_p___s_c_a_n___i_n_t_e_r_v_a_l_s" ],
    [ "GAP Scan window max and min", "group___b_l_e___g_a_p___s_c_a_n___w_i_n_d_o_w.html", "group___b_l_e___g_a_p___s_c_a_n___w_i_n_d_o_w" ],
    [ "GAP Scan timeout max and min", "group___b_l_e___g_a_p___s_c_a_n___t_i_m_e_o_u_t.html", "group___b_l_e___g_a_p___s_c_a_n___t_i_m_e_o_u_t" ],
    [ "GAP Minimum scanner buffer size", "group___b_l_e___g_a_p___s_c_a_n___b_u_f_f_e_r___s_i_z_e.html", "group___b_l_e___g_a_p___s_c_a_n___b_u_f_f_e_r___s_i_z_e" ],
    [ "GAP Advertising data status", "group___b_l_e___g_a_p___a_d_v___d_a_t_a___s_t_a_t_u_s.html", "group___b_l_e___g_a_p___a_d_v___d_a_t_a___s_t_a_t_u_s" ],
    [ "GAP Scanner filter policies", "group___b_l_e___g_a_p___s_c_a_n___f_i_l_t_e_r___p_o_l_i_c_i_e_s.html", "group___b_l_e___g_a_p___s_c_a_n___f_i_l_t_e_r___p_o_l_i_c_i_e_s" ],
    [ "Quality of Service (QoS) Channel survey interval defines", "group___b_l_e___g_a_p___q_o_s___c_h_a_n_n_e_l___s_u_r_v_e_y___i_n_t_e_r_v_a_l_s.html", "group___b_l_e___g_a_p___q_o_s___c_h_a_n_n_e_l___s_u_r_v_e_y___i_n_t_e_r_v_a_l_s" ],
    [ "BLE_GAP_ADDR_LEN", "group___b_l_e___g_a_p___d_e_f_i_n_e_s.html#ga65d5382341d5a38c5a051ac7198ddb03", null ],
    [ "BLE_GAP_ADDR_LEN", "group___b_l_e___g_a_p___d_e_f_i_n_e_s.html#ga65d5382341d5a38c5a051ac7198ddb03", null ],
    [ "BLE_GAP_ADDR_LEN", "group___b_l_e___g_a_p___d_e_f_i_n_e_s.html#ga65d5382341d5a38c5a051ac7198ddb03", null ],
    [ "BLE_GAP_ADV_REPORT_SET_ID_NOT_AVAILABLE", "group___b_l_e___g_a_p___d_e_f_i_n_e_s.html#ga66861a3460454c1f8ce390e9d341c572", null ],
    [ "BLE_GAP_ADV_REPORT_SET_ID_NOT_AVAILABLE", "group___b_l_e___g_a_p___d_e_f_i_n_e_s.html#ga66861a3460454c1f8ce390e9d341c572", null ],
    [ "BLE_GAP_ADV_REPORT_SET_ID_NOT_AVAILABLE", "group___b_l_e___g_a_p___d_e_f_i_n_e_s.html#ga66861a3460454c1f8ce390e9d341c572", null ],
    [ "BLE_GAP_ADV_SET_COUNT_DEFAULT", "group___b_l_e___g_a_p___d_e_f_i_n_e_s.html#gafd4069e30013244d38c7e481758cb395", null ],
    [ "BLE_GAP_ADV_SET_COUNT_DEFAULT", "group___b_l_e___g_a_p___d_e_f_i_n_e_s.html#gafd4069e30013244d38c7e481758cb395", null ],
    [ "BLE_GAP_ADV_SET_COUNT_DEFAULT", "group___b_l_e___g_a_p___d_e_f_i_n_e_s.html#gafd4069e30013244d38c7e481758cb395", null ],
    [ "BLE_GAP_ADV_SET_COUNT_MAX", "group___b_l_e___g_a_p___d_e_f_i_n_e_s.html#gab7bf833289d5556cf9c44fa2cf22a7ed", null ],
    [ "BLE_GAP_ADV_SET_COUNT_MAX", "group___b_l_e___g_a_p___d_e_f_i_n_e_s.html#gab7bf833289d5556cf9c44fa2cf22a7ed", null ],
    [ "BLE_GAP_ADV_SET_COUNT_MAX", "group___b_l_e___g_a_p___d_e_f_i_n_e_s.html#gab7bf833289d5556cf9c44fa2cf22a7ed", null ],
    [ "BLE_GAP_ADV_SET_HANDLE_NOT_SET", "group___b_l_e___g_a_p___d_e_f_i_n_e_s.html#ga0eb9ee787b529e0ba613cba8c7b1a3c9", null ],
    [ "BLE_GAP_ADV_SET_HANDLE_NOT_SET", "group___b_l_e___g_a_p___d_e_f_i_n_e_s.html#ga0eb9ee787b529e0ba613cba8c7b1a3c9", null ],
    [ "BLE_GAP_ADV_SET_HANDLE_NOT_SET", "group___b_l_e___g_a_p___d_e_f_i_n_e_s.html#ga0eb9ee787b529e0ba613cba8c7b1a3c9", null ],
    [ "BLE_GAP_CHANNEL_COUNT", "group___b_l_e___g_a_p___d_e_f_i_n_e_s.html#gac902386fab5e3f5dab89197300d58a17", null ],
    [ "BLE_GAP_CHANNEL_COUNT", "group___b_l_e___g_a_p___d_e_f_i_n_e_s.html#gac902386fab5e3f5dab89197300d58a17", null ],
    [ "BLE_GAP_CONN_COUNT_DEFAULT", "group___b_l_e___g_a_p___d_e_f_i_n_e_s.html#ga0d45d2b4f2c0c2d8449369204e533a15", null ],
    [ "BLE_GAP_CONN_COUNT_DEFAULT", "group___b_l_e___g_a_p___d_e_f_i_n_e_s.html#ga0d45d2b4f2c0c2d8449369204e533a15", null ],
    [ "BLE_GAP_CONN_COUNT_DEFAULT", "group___b_l_e___g_a_p___d_e_f_i_n_e_s.html#ga0d45d2b4f2c0c2d8449369204e533a15", null ],
    [ "BLE_GAP_DATA_LENGTH_AUTO", "group___b_l_e___g_a_p___d_e_f_i_n_e_s.html#gacb2c93761f970580b158e25192802474", null ],
    [ "BLE_GAP_DATA_LENGTH_AUTO", "group___b_l_e___g_a_p___d_e_f_i_n_e_s.html#gacb2c93761f970580b158e25192802474", null ],
    [ "BLE_GAP_DEFAULT_PRIVATE_ADDR_CYCLE_INTERVAL_S", "group___b_l_e___g_a_p___d_e_f_i_n_e_s.html#ga09366f020307b3079d1038062b7e162d", null ],
    [ "BLE_GAP_DEFAULT_PRIVATE_ADDR_CYCLE_INTERVAL_S", "group___b_l_e___g_a_p___d_e_f_i_n_e_s.html#ga09366f020307b3079d1038062b7e162d", null ],
    [ "BLE_GAP_DEFAULT_PRIVATE_ADDR_CYCLE_INTERVAL_S", "group___b_l_e___g_a_p___d_e_f_i_n_e_s.html#ga09366f020307b3079d1038062b7e162d", null ],
    [ "BLE_GAP_DEVICE_IDENTITIES_MAX_COUNT", "group___b_l_e___g_a_p___d_e_f_i_n_e_s.html#ga0f6932b0d1f53ba5b0c800b2eb54a6da", null ],
    [ "BLE_GAP_DEVICE_IDENTITIES_MAX_COUNT", "group___b_l_e___g_a_p___d_e_f_i_n_e_s.html#ga0f6932b0d1f53ba5b0c800b2eb54a6da", null ],
    [ "BLE_GAP_DEVICE_IDENTITIES_MAX_COUNT", "group___b_l_e___g_a_p___d_e_f_i_n_e_s.html#ga0f6932b0d1f53ba5b0c800b2eb54a6da", null ],
    [ "BLE_GAP_LESC_DHKEY_LEN", "group___b_l_e___g_a_p___d_e_f_i_n_e_s.html#ga4119ee2c5d3420c4d00fb7ea893d7579", null ],
    [ "BLE_GAP_LESC_DHKEY_LEN", "group___b_l_e___g_a_p___d_e_f_i_n_e_s.html#ga4119ee2c5d3420c4d00fb7ea893d7579", null ],
    [ "BLE_GAP_LESC_DHKEY_LEN", "group___b_l_e___g_a_p___d_e_f_i_n_e_s.html#ga4119ee2c5d3420c4d00fb7ea893d7579", null ],
    [ "BLE_GAP_LESC_P256_PK_LEN", "group___b_l_e___g_a_p___d_e_f_i_n_e_s.html#gadece65ccc255039bc9632cae8d457f45", null ],
    [ "BLE_GAP_LESC_P256_PK_LEN", "group___b_l_e___g_a_p___d_e_f_i_n_e_s.html#gadece65ccc255039bc9632cae8d457f45", null ],
    [ "BLE_GAP_LESC_P256_PK_LEN", "group___b_l_e___g_a_p___d_e_f_i_n_e_s.html#gadece65ccc255039bc9632cae8d457f45", null ],
    [ "BLE_GAP_MAX_PRIVATE_ADDR_CYCLE_INTERVAL_S", "group___b_l_e___g_a_p___d_e_f_i_n_e_s.html#ga5a37c22c1cc809772c93d4c6a21a0aef", null ],
    [ "BLE_GAP_MAX_PRIVATE_ADDR_CYCLE_INTERVAL_S", "group___b_l_e___g_a_p___d_e_f_i_n_e_s.html#ga5a37c22c1cc809772c93d4c6a21a0aef", null ],
    [ "BLE_GAP_MAX_PRIVATE_ADDR_CYCLE_INTERVAL_S", "group___b_l_e___g_a_p___d_e_f_i_n_e_s.html#ga5a37c22c1cc809772c93d4c6a21a0aef", null ],
    [ "BLE_GAP_PASSKEY_LEN", "group___b_l_e___g_a_p___d_e_f_i_n_e_s.html#ga3dee2b04fc5019675a630ee251c31d14", null ],
    [ "BLE_GAP_PASSKEY_LEN", "group___b_l_e___g_a_p___d_e_f_i_n_e_s.html#ga3dee2b04fc5019675a630ee251c31d14", null ],
    [ "BLE_GAP_PASSKEY_LEN", "group___b_l_e___g_a_p___d_e_f_i_n_e_s.html#ga3dee2b04fc5019675a630ee251c31d14", null ],
    [ "BLE_GAP_POWER_LEVEL_INVALID", "group___b_l_e___g_a_p___d_e_f_i_n_e_s.html#gacd3b0ebb45c173af598a482476d96b02", null ],
    [ "BLE_GAP_POWER_LEVEL_INVALID", "group___b_l_e___g_a_p___d_e_f_i_n_e_s.html#gacd3b0ebb45c173af598a482476d96b02", null ],
    [ "BLE_GAP_POWER_LEVEL_INVALID", "group___b_l_e___g_a_p___d_e_f_i_n_e_s.html#gacd3b0ebb45c173af598a482476d96b02", null ],
    [ "BLE_GAP_RSSI_THRESHOLD_INVALID", "group___b_l_e___g_a_p___d_e_f_i_n_e_s.html#gaaf406598e375512d38d7baf1087caf65", null ],
    [ "BLE_GAP_RSSI_THRESHOLD_INVALID", "group___b_l_e___g_a_p___d_e_f_i_n_e_s.html#gaaf406598e375512d38d7baf1087caf65", null ],
    [ "BLE_GAP_RSSI_THRESHOLD_INVALID", "group___b_l_e___g_a_p___d_e_f_i_n_e_s.html#gaaf406598e375512d38d7baf1087caf65", null ],
    [ "BLE_GAP_SEC_KEY_LEN", "group___b_l_e___g_a_p___d_e_f_i_n_e_s.html#gae54d6eefffc70a3ded9ebbede87e6a51", null ],
    [ "BLE_GAP_SEC_KEY_LEN", "group___b_l_e___g_a_p___d_e_f_i_n_e_s.html#gae54d6eefffc70a3ded9ebbede87e6a51", null ],
    [ "BLE_GAP_SEC_KEY_LEN", "group___b_l_e___g_a_p___d_e_f_i_n_e_s.html#gae54d6eefffc70a3ded9ebbede87e6a51", null ],
    [ "BLE_GAP_SEC_RAND_LEN", "group___b_l_e___g_a_p___d_e_f_i_n_e_s.html#gacd05838a6eaa17fae62eabfd26e25eb6", null ],
    [ "BLE_GAP_SEC_RAND_LEN", "group___b_l_e___g_a_p___d_e_f_i_n_e_s.html#gacd05838a6eaa17fae62eabfd26e25eb6", null ],
    [ "BLE_GAP_SEC_RAND_LEN", "group___b_l_e___g_a_p___d_e_f_i_n_e_s.html#gacd05838a6eaa17fae62eabfd26e25eb6", null ],
    [ "BLE_GAP_WHITELIST_ADDR_MAX_COUNT", "group___b_l_e___g_a_p___d_e_f_i_n_e_s.html#ga0e1bde4f7e3b124dc8aa2e7b032b8313", null ],
    [ "BLE_GAP_WHITELIST_ADDR_MAX_COUNT", "group___b_l_e___g_a_p___d_e_f_i_n_e_s.html#ga0e1bde4f7e3b124dc8aa2e7b032b8313", null ],
    [ "BLE_GAP_WHITELIST_ADDR_MAX_COUNT", "group___b_l_e___g_a_p___d_e_f_i_n_e_s.html#ga0e1bde4f7e3b124dc8aa2e7b032b8313", null ]
];