var group__nrfx__drivers =
[
    [ "ADC", "group__nrf__adc.html", "group__nrf__adc" ],
    [ "CLOCK", "group__nrf__clock.html", "group__nrf__clock" ],
    [ "COMP", "group__nrf__comp.html", "group__nrf__comp" ],
    [ "ECB", "group__nrf__ecb.html", "group__nrf__ecb" ],
    [ "GPIO", "group__nrf__gpio.html", "group__nrf__gpio" ],
    [ "GPIOTE", "group__nrf__gpiote.html", "group__nrf__gpiote" ],
    [ "I2S", "group__nrf__i2s.html", "group__nrf__i2s" ],
    [ "LPCOMP", "group__nrf__lpcomp.html", "group__nrf__lpcomp" ],
    [ "NVMC", "group__nrf__nvmc.html", "group__nrf__nvmc" ],
    [ "PDM", "group__nrf__pdm.html", "group__nrf__pdm" ],
    [ "POWER", "group__nrf__power.html", "group__nrf__power" ],
    [ "PPI", "group__nrf__ppi.html", "group__nrf__ppi" ],
    [ "PWM", "group__nrf__pwm.html", "group__nrf__pwm" ],
    [ "QDEC", "group__nrf__qdec.html", "group__nrf__qdec" ],
    [ "QSPI", "group__nrf__qspi.html", "group__nrf__qspi" ],
    [ "RNG", "group__nrf__rng.html", "group__nrf__rng" ],
    [ "RTC", "group__nrf__rtc.html", "group__nrf__rtc" ],
    [ "SAADC", "group__nrf__saadc.html", "group__nrf__saadc" ],
    [ "SPI", "group__nrf__spi.html", "group__nrf__spi" ],
    [ "SPIM", "group__nrf__spim.html", "group__nrf__spim" ],
    [ "SPIS", "group__nrf__spis.html", "group__nrf__spis" ],
    [ "Cortex-M Systick", "group__nrf__systick.html", "group__nrf__systick" ],
    [ "SWI/EGU", "group__nrf__swi__egu.html", "group__nrf__swi__egu" ],
    [ "TEMP", "group__nrf__temp.html", "group__nrf__temp" ],
    [ "TIMER", "group__nrf__timer.html", "group__nrf__timer" ],
    [ "TWI", "group__nrf__twi.html", "group__nrf__twi" ],
    [ "TWIM", "group__nrf__twim.html", "group__nrf__twim" ],
    [ "TWIS", "group__nrf__twis.html", "group__nrf__twis" ],
    [ "UART", "group__nrf__uart.html", "group__nrf__uart" ],
    [ "UARTE", "group__nrf__uarte.html", "group__nrf__uarte" ],
    [ "USBD", "group__nrf__usbd.html", "group__nrf__usbd" ],
    [ "WDT", "group__nrf__wdt.html", "group__nrf__wdt" ]
];