var searchData=
[
  ['base_20defined_20for_20sdk_20modules_76053',['Base defined for SDK Modules',['../group__sdk__err__base.html',1,'']]],
  ['basic_20math_20functions_76054',['Basic Math Functions',['../group__group_math.html',1,'']]],
  ['battery_20service_76055',['Battery Service',['../group__ble__bas.html',1,'']]],
  ['battery_20service_20client_76056',['Battery Service Client',['../group__ble__bas__c.html',1,'']]],
  ['bilinear_20interpolation_76057',['Bilinear Interpolation',['../group___bilinear_interpolate.html',1,'']]],
  ['bitmask_20module_76058',['Bitmask module',['../group__nrf__bitmask.html',1,'']]],
  ['ble_20advertisements_76059',['BLE Advertisements',['../group__group__ble__adv.html',1,'']]],
  ['ble_20connection_20handles_76060',['BLE Connection Handles',['../group___b_l_e___c_o_n_n___h_a_n_d_l_e_s.html',1,'']]],
  ['ble_20connection_20state_20functions_76061',['BLE connection state functions',['../group__ble__conn__state__functions.html',1,'']]],
  ['ble_20date_20time_20characteristic_20type_76062',['BLE Date Time characteristic type',['../group__ble__sdk__srv__date__time.html',1,'']]],
  ['ble_20lesc_20module_76063',['BLE LESC module',['../group__ble__lesc.html',1,'']]],
  ['ble_20link_20context_20manager_76064',['BLE Link Context Manager',['../group__ble__link__ctx__manager.html',1,'']]],
  ['ble_20pairing_20messages_76065',['BLE pairing messages',['../group__nfc__ble__pair__msg.html',1,'']]],
  ['ble_20softdevice_20common_76066',['BLE SoftDevice Common',['../group___b_l_e___c_o_m_m_o_n.html',1,'']]],
  ['ble_20support_20in_20softdevice_20handler_76067',['BLE support in SoftDevice Handler',['../group__nrf__sdh__ble.html',1,'']]],
  ['ble_20uart_20command_20line_20interface_20transport_20layer_76068',['BLE UART command line interface transport layer',['../group__nrf__cli__ble__uart.html',1,'']]],
  ['block_20device_76069',['Block device',['../group__nrf__block__dev.html',1,'']]],
  ['block_20memory_20allocator_76070',['Block memory allocator',['../group__nrf__balloc.html',1,'']]],
  ['blood_20pressure_20service_76071',['Blood Pressure Service',['../group__ble__bps.html',1,'']]],
  ['bluetooth_20appearance_20values_76072',['Bluetooth Appearance values',['../group___b_l_e___a_p_p_e_a_r_a_n_c_e_s.html',1,'']]],
  ['bluetooth_20status_20codes_76073',['Bluetooth status codes',['../group___b_l_e___h_c_i___s_t_a_t_u_s___c_o_d_e_s.html',1,'']]],
  ['bluey_20rev_201_2e1_76074',['Bluey rev 1.1',['../group__board__bluey__1v1.html',1,'']]],
  ['bms_20feature_20bits_76075',['BMS feature bits',['../group___n_r_f___b_l_e___b_m_s___f_e_a_t_u_r_e_s.html',1,'']]],
  ['board_20initialization_20flags_2e_76076',['Board initialization flags.',['../group___b_s_p___b_o_a_r_d___i_n_i_t___f_l_a_g_s.html',1,'']]],
  ['board_20support_20package_76077',['Board Support Package',['../group__bsp.html',1,'']]],
  ['bond_20management_20service_76078',['Bond Management Service',['../group__ble__bms.html',1,'']]],
  ['bootloader_20information_76079',['Bootloader Information',['../group__nrf__bootloader__info.html',1,'']]],
  ['bootloader_20modules_76080',['Bootloader modules',['../group__nrf__bootloader.html',1,'']]],
  ['bsp_20over_20cli_20module_76081',['BSP over CLI Module',['../group__bsp__cli.html',1,'']]],
  ['bsp_3a_20ant_20button_20module_76082',['BSP: ANT Button Module',['../group__bsp__btn__ant.html',1,'']]],
  ['bsp_3a_20ble_20button_20module_76083',['BSP: BLE Button Module',['../group__bsp__btn__ble.html',1,'']]],
  ['button_20handler_76084',['Button Handler',['../group__app__button.html',1,'']]],
  ['buttonless_20dfu_20service_76085',['Buttonless DFU Service',['../group__ble__dfu.html',1,'']]]
];
